[goldmark]
  [goldmark.renderer]
    unsafe = true

[tableOfContents]
startLevel = 2
endLevel = 4
ordered = true

[highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = true
tabWidth = 4
